# Generated by Django 5.2.1 on 2025-06-08 09:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yksshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('password_hash', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=6)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('otp_created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
